# Site
name: "MapelliSpotted"
title: "MapelliSpotted"
description: "Benvenuto nel nostro blog!"
logo: 'assets/images/logo/MS_logo_color.png'
favicon: 'assets/images/logo/favicon.ico'
baseurl:
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: redazione@mapelli-monza.edu.it

# Authors
authors:
  alexandra:
    name: Alexandra
    display_name: Alexandra
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  alonso:
    name: Alonso
    display_name: Alonso
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  chiara:
    name: Chiara
    display_name: Chiara
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  chris:
    name: Chris
    display_name: Chris
    avatar: 'assets/images/avatar/cb.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "Sportivo, amante del tennis e grande tifoso di calcio."
  christian:
    name: Christian
    display_name: Christian
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  elisa:
    name: Elisa
    display_name: Elisa
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  enri:
    name: Enri
    display_name: Enri
    avatar: 'assets/images/avatar/eo.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  aleilfacinoroso:
    name: L'Orsetto Fa(s)cinoroso
    display_name: L'Orsetto Fa(s)cinoroso
    avatar: 'assets/images/avatar/ap.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  emanuele:
    name: Emanuele
    display_name: Emanuele
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  fabio:
    name: Fabio
    display_name: Fabio
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  giacomo:
    name: Giacomo
    display_name: Giacomo
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  ilgualto:
    name: Il Gualto
    display_name: Il Gualto
    avatar: 'assets/images/avatar/ilgualto.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "Appassionato di automobili e Alfista nel cuore, nel tempo libero scatto foto all'Autodromo di Monza."
  labionda:
    name: La Bionda
    display_name: La Bionda
    avatar: 'assets/images/avatar/labionda.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "Mi piace leggere e disegnare, guardare film e serie-tv ma soprattutto mi piace seguire la moda. Durante il periodo natalizio cerco di visitare più mercatini di Natale possibile e aiutarvi con i regali per i vostri cari."
  lorenzo:
    name: Lorenzo
    display_name: Jeremy
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  luca:
    name: Luca
    display_name: Luca
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  luke:
    name: Luke
    display_name: Luke
    avatar: 'assets/images/avatar/luke.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "Sono sportivo: basket, MTB, downhill, windsurf, vela e sci. Mi piace stare in compagnia, sono curioso e mi sveglio sempre di buon umore. Sono un ragazzo chill."
  marcoianne:
    name: Marco
    display_name: Marco
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  marzia:
    name: Marzia
    display_name: Marzia
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: ""
  nicolo:
    name: Nicolò
    display_name: Nicolò
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: ""
  redazione:
    name: La Redazione
    display_name: La Redazione
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: ""
  sara:
    name: Sara
    display_name: Sara
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  silvia:
    name: Silvia
    display_name: Silvia
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  simo:
    name: Simo
    display_name: Simo
    avatar: 'assets/images/avatar/sm.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "Appassionato di arte rinascimentale e numismatica, adoro visitare musei e avvicinare le persone alle mie passioni!"
  simone:
    name: Simone
    display_name: Simone
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  ste:
    name: Stefano Caglio
    display_name: SC
    avatar: 'assets/images/avatar/SC.png'
    email: stefano.caglio@mapelli-monza.edu.it
    web: https://stefanocaglio.it
    instagram: https://instagram.com/stefanocaglio
    description: "-"
  suongminh:
    name: Suong Minh
    display_name: Suong Minh
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  tommy:
    name: Tommy
    display_name: Tommy
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
  viola:
    name: Viola
    display_name: Viola
    avatar: 'assets/images/avatar/empty.png'
    email: redazione@mapelli-monza.edu.it
    web: https://mapellispotted.github.io
    instagram: https://instagram.com/
    description: "-"
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
